version: '3.8'

x-airflow-common:
  &airflow-common
  build: .
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
    # Mount point reference for the DAG file
    - PROJECT_DIR=/opt/airflow/project
    # Automatically accept airflow metadata DB tracking
    - _AIRFLOW_DB_UPGRADE=true
    - _AIRFLOW_WWW_USER_CREATE=true
    - _AIRFLOW_WWW_USER_USERNAME=admin
    - _AIRFLOW_WWW_USER_PASSWORD=admin
    - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/project/config/secrets/aws-gcp-migration-490909-f373c57a6188.json
    # Install additional requirements automatically on startup
    - _PIP_ADDITIONAL_REQUIREMENTS=google-cloud-bigquery dbt-bigquery pyspark delta-spark boto3 pyarrow python-dotenv
  volumes:
    # Mount the dags folder into the container
    - ./dags:/opt/airflow/dags
    # Mount the ENTIRE repository to /opt/airflow/project so Python scripts are reachable
    - ../:/opt/airflow/project
    - ./logs:/opt/airflow/logs
  user: "${AIRFLOW_UID:-50000}:0"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    command: version
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres-db-volume:
