bigquery_migration_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: aws-gcp-migration-490909
      dataset: analytics
      threads: 1
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
